parking_homepage:
    path:      /
    defaults:  { _controller: ParkinkBundle:Default:index }
    
parkink:
    resource: "@ParkinkBundle/Controller/DefaultController.php"
    type:     annotation
    prefix:   /

parkink_place:
    resource: "@ParkinkBundle/Controller/PlaceController.php"
    type:     annotation
    prefix: /
    
panier:
    resource: "@ParkinkBundle/Controller/PanierController.php"
    type:     annotation
    prefix:   /panier
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    type: xml

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    type: xml
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    type: xml
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    type: xml
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    type: xml
    prefix: /profile