security:
    encoders:
        UserBundle\Entity\User: 
            algorithm: bcrypt
            iterations: 5000
    
    providers:

        main:
            id: fos_user.user_provider.username            

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
     
        main:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                
            logout:
                path: fos_user_security_logout
                target: parking_home
            remember_me:
                key:        %secret%
        login:
            # Toute page de connexion
            pattern:  ^/login$
            anonymous: true
           
           
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }
